#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedMetadata
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum abc_employee_abc_hobby
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reading = 745780000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		cooking = 745780001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		travelling = 745780002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		drawing = 745780003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		cricket = 745780004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		chess = 745780005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		singing = 745780006,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum abc_employee_abc_jobtitle
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Developer = 745780000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QA = 745780001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Manager = 745780002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Support = 745780003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Analyst = 745780004,
	}
	
	/// <summary>
	/// Status of the Employee
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum abc_employee_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Employee
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum abc_employee_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("abc_employee")]
	public partial class abc_Employee : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public abc_Employee() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "abc_employee";
		
		public const string EntityLogicalCollectionName = "abc_employees";
		
		public const string EntitySetName = "abc_employees";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_address")]
		public string abc_Address
		{
			get
			{
				return this.GetAttributeValue<string>("abc_address");
			}
			set
			{
				this.SetAttributeValue("abc_address", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_city")]
		public string abc_City
		{
			get
			{
				return this.GetAttributeValue<string>("abc_city");
			}
			set
			{
				this.SetAttributeValue("abc_city", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_contactno")]
		public System.Nullable<int> abc_ContactNo
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("abc_contactno");
			}
			set
			{
				this.SetAttributeValue("abc_contactno", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_cv")]
		public System.Nullable<System.Guid> abc_CV
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("abc_cv");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_districtname")]
		public Microsoft.Xrm.Sdk.EntityReference abc_DistrictName
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("abc_districtname");
			}
			set
			{
				this.SetAttributeValue("abc_districtname", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_email")]
		public string abc_email
		{
			get
			{
				return this.GetAttributeValue<string>("abc_email");
			}
			set
			{
				this.SetAttributeValue("abc_email", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_empdob")]
		public System.Nullable<System.DateTime> abc_EmpDob
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("abc_empdob");
			}
			set
			{
				this.SetAttributeValue("abc_empdob", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_employeeid")]
		public System.Nullable<System.Guid> abc_EmployeeId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("abc_employeeid");
			}
			set
			{
				this.SetAttributeValue("abc_employeeid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_employeeid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.abc_EmployeeId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_employeename")]
		public string abc_EmployeeName
		{
			get
			{
				return this.GetAttributeValue<string>("abc_employeename");
			}
			set
			{
				this.SetAttributeValue("abc_employeename", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_experience")]
		public System.Nullable<int> abc_experience
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("abc_experience");
			}
			set
			{
				this.SetAttributeValue("abc_experience", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_gender")]
		public System.Nullable<bool> abc_Gender
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("abc_gender");
			}
			set
			{
				this.SetAttributeValue("abc_gender", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_grosssalary")]
		public System.Nullable<decimal> abc_GrossSalary
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("abc_grosssalary");
			}
			set
			{
				this.SetAttributeValue("abc_grosssalary", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_hobby")]
		public virtual System.Collections.Generic.IEnumerable<abc_employee_abc_hobby> abc_Hobby
		{
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<abc_employee_abc_hobby>(this, "abc_hobby");
			}
			set
			{
				this.SetAttributeValue("abc_hobby", EntityOptionSetEnum.GetMultiEnum(this, "abc_hobby", value));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_isemployeeinmetrocity")]
		public System.Nullable<bool> abc_isEmployeeInMetroCity
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("abc_isemployeeinmetrocity");
			}
			set
			{
				this.SetAttributeValue("abc_isemployeeinmetrocity", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_jobtitle")]
		public virtual abc_employee_abc_jobtitle? abc_JobTitle
		{
			get
			{
				return ((abc_employee_abc_jobtitle?)(EntityOptionSetEnum.GetEnum(this, "abc_jobtitle")));
			}
			set
			{
				this.SetAttributeValue("abc_jobtitle", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_joiningdate")]
		public System.Nullable<System.DateTime> abc_JoiningDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("abc_joiningdate");
			}
			set
			{
				this.SetAttributeValue("abc_joiningdate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_profileimage")]
		public byte[] abc_ProfileImage
		{
			get
			{
				return this.GetAttributeValue<byte[]>("abc_profileimage");
			}
			set
			{
				this.SetAttributeValue("abc_profileimage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_profileimage_timestamp")]
		public System.Nullable<long> abc_ProfileImage_Timestamp
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("abc_profileimage_timestamp");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_profileimage_url")]
		public string abc_ProfileImage_URL
		{
			get
			{
				return this.GetAttributeValue<string>("abc_profileimage_url");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_profileimageid")]
		public System.Nullable<System.Guid> abc_ProfileImageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("abc_profileimageid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_salary")]
		public System.Nullable<decimal> abc_Salary
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("abc_salary");
			}
			set
			{
				this.SetAttributeValue("abc_salary", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_statename")]
		public Microsoft.Xrm.Sdk.EntityReference abc_StateName
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("abc_statename");
			}
			set
			{
				this.SetAttributeValue("abc_statename", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_terminationdate")]
		public System.Nullable<System.DateTime> abc_TerminationDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("abc_terminationdate");
			}
			set
			{
				this.SetAttributeValue("abc_terminationdate", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Employee
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual abc_employee_statecode? statecode
		{
			get
			{
				return ((abc_employee_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Employee
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual abc_employee_statuscode? statuscode
		{
			get
			{
				return ((abc_employee_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 abc_employee_DistrictName_abc_district
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_districtname")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("abc_employee_DistrictName_abc_district")]
		public SharedMetadata.abc_District abc_employee_DistrictName_abc_district
		{
			get
			{
				return this.GetRelatedEntity<SharedMetadata.abc_District>("abc_employee_DistrictName_abc_district", null);
			}
			set
			{
				this.SetRelatedEntity<SharedMetadata.abc_District>("abc_employee_DistrictName_abc_district", null, value);
			}
		}
		
		/// <summary>
		/// N:1 abc_employee_StateName_abc_state
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_statename")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("abc_employee_StateName_abc_state")]
		public SharedMetadata.abc_State abc_employee_StateName_abc_state
		{
			get
			{
				return this.GetRelatedEntity<SharedMetadata.abc_State>("abc_employee_StateName_abc_state", null);
			}
			set
			{
				this.SetRelatedEntity<SharedMetadata.abc_State>("abc_employee_StateName_abc_state", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
