#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedMetadata
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum abc_state_abc_region
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		East = 745780000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		West = 745780001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		North = 745780002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		South = 745780003,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum abc_state_abc_statetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		State = 745780000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnionTerritory = 745780001,
	}
	
	/// <summary>
	/// Status of the State
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum abc_state_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the State
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum abc_state_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("abc_state")]
	public partial class abc_State : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public abc_State() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "abc_state";
		
		public const string EntityLogicalCollectionName = "abc_states";
		
		public const string EntitySetName = "abc_states";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_area")]
		public System.Nullable<decimal> abc_area
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("abc_area");
			}
			set
			{
				this.SetAttributeValue("abc_area", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_capital")]
		public string abc_Capital
		{
			get
			{
				return this.GetAttributeValue<string>("abc_capital");
			}
			set
			{
				this.SetAttributeValue("abc_capital", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_capitalcity")]
		public string abc_capitalcity
		{
			get
			{
				return this.GetAttributeValue<string>("abc_capitalcity");
			}
			set
			{
				this.SetAttributeValue("abc_capitalcity", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_formationdate")]
		public System.Nullable<System.DateTime> abc_formationdate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("abc_formationdate");
			}
			set
			{
				this.SetAttributeValue("abc_formationdate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_gststatecode")]
		public System.Nullable<int> abc_gststatecode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("abc_gststatecode");
			}
			set
			{
				this.SetAttributeValue("abc_gststatecode", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_isspecialcategory")]
		public System.Nullable<bool> abc_isspecialcategory
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("abc_isspecialcategory");
			}
			set
			{
				this.SetAttributeValue("abc_isspecialcategory", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_literacyrate")]
		public System.Nullable<decimal> abc_literacyrate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("abc_literacyrate");
			}
			set
			{
				this.SetAttributeValue("abc_literacyrate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_officiallanguage")]
		public string abc_officiallanguage
		{
			get
			{
				return this.GetAttributeValue<string>("abc_officiallanguage");
			}
			set
			{
				this.SetAttributeValue("abc_officiallanguage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_population")]
		public System.Nullable<int> abc_Population
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("abc_population");
			}
			set
			{
				this.SetAttributeValue("abc_population", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_region")]
		public virtual abc_state_abc_region? abc_Region
		{
			get
			{
				return ((abc_state_abc_region?)(EntityOptionSetEnum.GetEnum(this, "abc_region")));
			}
			set
			{
				this.SetAttributeValue("abc_region", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_statecode")]
		public string abc_StateCode
		{
			get
			{
				return this.GetAttributeValue<string>("abc_statecode");
			}
			set
			{
				this.SetAttributeValue("abc_statecode", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_statefemalepopulation")]
		public System.Nullable<int> abc_StateFemalepopulation
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("abc_statefemalepopulation");
			}
		}
		
		/// <summary>
		/// Last Updated time of rollup field StateFemalepopulation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_statefemalepopulation_date")]
		public System.Nullable<System.DateTime> abc_StateFemalepopulation_Date
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("abc_statefemalepopulation_date");
			}
		}
		
		/// <summary>
		/// State of rollup field StateFemalepopulation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_statefemalepopulation_state")]
		public System.Nullable<int> abc_StateFemalepopulation_State
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("abc_statefemalepopulation_state");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_stateid")]
		public System.Nullable<System.Guid> abc_StateId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("abc_stateid");
			}
			set
			{
				this.SetAttributeValue("abc_stateid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_stateid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.abc_StateId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_statemalepopulation")]
		public System.Nullable<int> abc_StateMalePopulation
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("abc_statemalepopulation");
			}
		}
		
		/// <summary>
		/// Last Updated time of rollup field StateMalePopulation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_statemalepopulation_date")]
		public System.Nullable<System.DateTime> abc_StateMalePopulation_Date
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("abc_statemalepopulation_date");
			}
		}
		
		/// <summary>
		/// State of rollup field StateMalePopulation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_statemalepopulation_state")]
		public System.Nullable<int> abc_StateMalePopulation_State
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("abc_statemalepopulation_state");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_statename")]
		public string abc_StateName
		{
			get
			{
				return this.GetAttributeValue<string>("abc_statename");
			}
			set
			{
				this.SetAttributeValue("abc_statename", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_statetotalpopulation")]
		public System.Nullable<decimal> abc_StateTotalPopulation
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("abc_statetotalpopulation");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_statetype")]
		public virtual abc_state_abc_statetype? abc_statetype
		{
			get
			{
				return ((abc_state_abc_statetype?)(EntityOptionSetEnum.GetEnum(this, "abc_statetype")));
			}
			set
			{
				this.SetAttributeValue("abc_statetype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the State
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual abc_state_statecode? statecode
		{
			get
			{
				return ((abc_state_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the State
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual abc_state_statuscode? statuscode
		{
			get
			{
				return ((abc_state_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N abc_district_state_abc_state
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("abc_district_state_abc_state")]
		public System.Collections.Generic.IEnumerable<SharedMetadata.abc_District> abc_district_state_abc_state
		{
			get
			{
				return this.GetRelatedEntities<SharedMetadata.abc_District>("abc_district_state_abc_state", null);
			}
			set
			{
				this.SetRelatedEntities<SharedMetadata.abc_District>("abc_district_state_abc_state", null, value);
			}
		}
		
		/// <summary>
		/// 1:N abc_employee_StateName_abc_state
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("abc_employee_StateName_abc_state")]
		public System.Collections.Generic.IEnumerable<SharedMetadata.abc_Employee> abc_employee_StateName_abc_state
		{
			get
			{
				return this.GetRelatedEntities<SharedMetadata.abc_Employee>("abc_employee_StateName_abc_state", null);
			}
			set
			{
				this.SetRelatedEntities<SharedMetadata.abc_Employee>("abc_employee_StateName_abc_state", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
