#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedMetadata
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum abc_district_abc_urbantype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Urban = 745780000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Semiurban = 745780001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rural = 745780002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Metropolitan = 745780003,
	}
	
	/// <summary>
	/// Status of the District
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum abc_district_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the District
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum abc_district_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("abc_district")]
	public partial class abc_District : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public abc_District() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "abc_district";
		
		public const string EntityLogicalCollectionName = "abc_districts";
		
		public const string EntitySetName = "abc_districts";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_areainsqkm")]
		public System.Nullable<decimal> abc_Areainsqkm
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("abc_areainsqkm");
			}
			set
			{
				this.SetAttributeValue("abc_areainsqkm", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_districtcode")]
		public string abc_districtcode
		{
			get
			{
				return this.GetAttributeValue<string>("abc_districtcode");
			}
			set
			{
				this.SetAttributeValue("abc_districtcode", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_districthq")]
		public string abc_DistrictHQ
		{
			get
			{
				return this.GetAttributeValue<string>("abc_districthq");
			}
			set
			{
				this.SetAttributeValue("abc_districthq", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_districtid")]
		public System.Nullable<System.Guid> abc_DistrictId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("abc_districtid");
			}
			set
			{
				this.SetAttributeValue("abc_districtid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_districtid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.abc_DistrictId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_districtname")]
		public string abc_DistrictName
		{
			get
			{
				return this.GetAttributeValue<string>("abc_districtname");
			}
			set
			{
				this.SetAttributeValue("abc_districtname", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_establisheddate")]
		public System.Nullable<System.DateTime> abc_establisheddate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("abc_establisheddate");
			}
			set
			{
				this.SetAttributeValue("abc_establisheddate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_femalepopulation")]
		public System.Nullable<int> abc_FemalePopulation
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("abc_femalepopulation");
			}
			set
			{
				this.SetAttributeValue("abc_femalepopulation", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_iscapitaldistrict")]
		public System.Nullable<bool> abc_iscapitaldistrict
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("abc_iscapitaldistrict");
			}
			set
			{
				this.SetAttributeValue("abc_iscapitaldistrict", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_malepopulation")]
		public System.Nullable<int> abc_MalePopulation
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("abc_malepopulation");
			}
			set
			{
				this.SetAttributeValue("abc_malepopulation", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_metrozonecode")]
		public string abc_metrozonecode
		{
			get
			{
				return this.GetAttributeValue<string>("abc_metrozonecode");
			}
			set
			{
				this.SetAttributeValue("abc_metrozonecode", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_noofblocks")]
		public System.Nullable<int> abc_NoofBlocks
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("abc_noofblocks");
			}
			set
			{
				this.SetAttributeValue("abc_noofblocks", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_population")]
		public System.Nullable<int> abc_population
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("abc_population");
			}
			set
			{
				this.SetAttributeValue("abc_population", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_state")]
		public Microsoft.Xrm.Sdk.EntityReference abc_state
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("abc_state");
			}
			set
			{
				this.SetAttributeValue("abc_state", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_taxoverride")]
		public System.Nullable<decimal> abc_taxoverride
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("abc_taxoverride");
			}
			set
			{
				this.SetAttributeValue("abc_taxoverride", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_totalpopulation")]
		public System.Nullable<decimal> abc_TotalPopulation
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("abc_totalpopulation");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_urbantype")]
		public virtual abc_district_abc_urbantype? abc_urbantype
		{
			get
			{
				return ((abc_district_abc_urbantype?)(EntityOptionSetEnum.GetEnum(this, "abc_urbantype")));
			}
			set
			{
				this.SetAttributeValue("abc_urbantype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the District
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual abc_district_statecode? statecode
		{
			get
			{
				return ((abc_district_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the District
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual abc_district_statuscode? statuscode
		{
			get
			{
				return ((abc_district_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N abc_employee_DistrictName_abc_district
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("abc_employee_DistrictName_abc_district")]
		public System.Collections.Generic.IEnumerable<SharedMetadata.abc_Employee> abc_employee_DistrictName_abc_district
		{
			get
			{
				return this.GetRelatedEntities<SharedMetadata.abc_Employee>("abc_employee_DistrictName_abc_district", null);
			}
			set
			{
				this.SetRelatedEntities<SharedMetadata.abc_Employee>("abc_employee_DistrictName_abc_district", null, value);
			}
		}
		
		/// <summary>
		/// N:1 abc_district_state_abc_state
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abc_state")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("abc_district_state_abc_state")]
		public SharedMetadata.abc_State abc_district_state_abc_state
		{
			get
			{
				return this.GetRelatedEntity<SharedMetadata.abc_State>("abc_district_state_abc_state", null);
			}
			set
			{
				this.SetRelatedEntity<SharedMetadata.abc_State>("abc_district_state_abc_state", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
