#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace SharedMetadata
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class OrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public OrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedMetadata.abc_District"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedMetadata.abc_District> abc_DistrictSet
		{
			get
			{
				return this.CreateQuery<SharedMetadata.abc_District>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedMetadata.abc_Employee"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedMetadata.abc_Employee> abc_EmployeeSet
		{
			get
			{
				return this.CreateQuery<SharedMetadata.abc_Employee>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedMetadata.abc_State"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedMetadata.abc_State> abc_StateSet
		{
			get
			{
				return this.CreateQuery<SharedMetadata.abc_State>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedMetadata.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedMetadata.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<SharedMetadata.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedMetadata.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedMetadata.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<SharedMetadata.Contact>();
			}
		}
	}
}
#pragma warning restore CS1591
